### ISSUE TITLE
Issue reading in data from .csv

### ISSUE THREAD

**Issue by nbgraham** [etag/D3_examples#1]
@jduckles 
I can't figure out how to read data in from a separate .csv file. I keep getting errors.

>XMLHttpRequest cannot load file:///C:/Users/Nicholas/Documents/GitHub/D3_examples/iris.csv. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource

I looked this error up and tried to set up a local server but I got a different error then.

>XMLHttpRequest cannot load http://127.0.0.1:8080/iris.csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by nbgraham** [comment]
I tried most things on [this wiki](https://github.com/mrdoob/three.js/wiki/How-to-run-things-locally) but I couldn't get anything to work.

**Comment by jduckles** [comment]
@nbgraham it is working for me ![plot](https://jduckles-dropshare.s3-us-west-2.amazonaws.com/Screen-Shot-2015-09-25-08-17-57.png)

**Comment by jduckles** [comment]
So your code is right, but how you're running your server might need some help.

**Comment by nbgraham** [comment]
Earlier, I couldn't get `python simplehttpserver` to work. So I did `npm install http-server` and `http-server` to set up my server. I just reinstalled Python (v 2.7) and made sure to add it to my system path. Now, `python simplehttpserver` works.  I set up the server and it logs the attempt to access iris.csv, but I am still getting the same error when I try to load the page.

![image](https://cloud.githubusercontent.com/assets/11163850/10102772/e7a8191a-6365-11e5-9fc0-711813bd41c4.png)

>XMLHttpRequest cannot load http://localhost:8000/iris.csv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
d3.min.js:3 Uncaught TypeError: Cannot read property 'length' of null

If I type http://localhost:8000/iris.csv into by address bar, I can download the file.

**Comment by jduckles** [comment]
What is the error you're getting in the browser?

**Comment by nbgraham** [comment]
I don't understand the question. I only get errors when I try to open index.html.

![image](https://cloud.githubusercontent.com/assets/11163850/10103653/bbfd22c4-636a-11e5-9669-67d8314b2770.png)

**Comment by jduckles** [comment]
in your browser bar where it says `file://C:/.....` you need you put `http://localhost:8000/index.html`

**Comment by jduckles** [comment]
You're running a web server on your local machine now `localhost` it is running on port 8000 `:8000` and the file is `index.html`

**Comment by nbgraham** [comment]
Thanks!
![image](https://cloud.githubusercontent.com/assets/11163850/10104192/f2546456-636d-11e5-9b50-3dc61f704c73.png)
