### ISSUE TITLE
Issues with scales and rectangle heights

### ISSUE THREAD

**Issue by nbgraham** [etag/D3_examples#2]
@jduckles 
I'm having trouble with [my bar chart](https://github.com/etag/D3_examples/tree/pop_demographics/Bar%20chart%20population).

I got a simple bar chart to work with the scale, but then I tried to add an age demographic split in each population bar. I cannot get the heights to work out with the scale. The heights of the inner rectangles becomes too large.

Also, should I keep looking over the [learning objectives](https://github.com/etag/etagapi/wiki), or do you have a task for me?

**Comment by jduckles** [comment]
Looks like a sign (+/-) issue, do you want this to be a stacked bar-plot?

**Comment by nbgraham** [comment]
Yes, that's what I'm working on right now. I was trying to have it be a regular bar chart and only show the breakdown when you hover over the bar, but I need to figure out the stacked bar chart first.

**Comment by nbgraham** [comment]
I got it to work with my [latest commit](../commit/54290c3af7b93cb3b676dfa98aee7cc83993c7af).
